updateInterval: 5m
privateKeyPath: /root/.ssh/id_ed25519
listen: :3333
projects:
  - type: docker_compose
    name: gitea-postgres
    repository: git@github.com:docker/awesome-compose.git
    branch: master
    updateInterval: 1m
    options:
      env-file: /etc/yggops/gitea.env
      build: false
